model_list:
  - model_name: "bedrock-3.5-haiku"
    litellm_params:
      model: "bedrock/us.anthropic.claude-3-5-haiku-20241022-v1:0"
  - model_name: "bedrock-3.5-sonnet-v2"
    litellm_params:
      model: "bedrock/us.anthropic.claude-3-5-sonnet-20241022-v2:0"
